### ISSUE TITLE
Extent of Support for windows phone 8.1 silverlight application

### ISSUE THREAD

**Issue by KonyLabs** [2gis/winphonedriver#49]
I came across this awesome tool, but just wanted to know what is the extent of support you guys are providing for windows phone 8.1 silverlight. Because in the description it says " Currently is implemented only limited subset of WebDriver JSON Wire protocol". 

And what is the status of this project. I guess its in end to end working condition ? With the minor changes i.e setting server in my AUT, i'll be good to go ? And it uses Selenium Driver(jars) to make driver call. Please correct me if i am wrong ? 
Thanks

**Comment by KonyLabs** [comment]
Hi,
I started using it. But i am not able to find "WindowsPhoneDriver.OuterDriver.exe" .
Please help me on it, stuck because of this.

**Comment by NickAb** [comment]
Hello @KonyLabs,

In short, it is a working project, to automate your app, you have to add InnerDriver package to you app and add initialisation code as stated in [README](https://github.com/2gis/winphonedriver/README.md).
`WindowsPhoneDriver.OuterDriver.exe` can be build from source, but if you don't want to build the project, then you can wait for next week, when I publish release myself.
Also slides and video of my talk about Winium.StoreApps (which is basically same driver, but for StoreApps instead of Silverlight) should be posted online soon.

This project has most of common commands needed for tests implemented. It was mostly tested with python as client language for tests, but we also tested against C# (so you should work with other Appium or Selenium bindings). Currently we are focused on developing StoreApps and CodedUI versions of Winium, but we support this version too, so if there any bugs, we can fix them. Also, sometimes we backport features from StoreApps to this project.

**Comment by KonyLabs** [comment]
Hi Nick,

I'll build myself until and unless there is any change in the next week release you are talking about. 
Moreover i'll be writing tests in Java. Will let you know if i come across any bug on it.
Thanks

**Comment by KonyLabs** [comment]
Hi Nick,

So, i started writing Test Case in Java. I am ble to launch the application but not able to find the element
Attaching logs and TestCase
<img width="1079" alt="screen shot 2015-09-14 at 1 56 55 pm" src="https://cloud.githubusercontent.com/assets/14196612/9845471/bd99b302-5ae8-11e5-9cb7-f02e71bee0fa.png">
<img width="1200" alt="screen shot 2015-09-14 at 1 59 49 pm" src="https://cloud.githubusercontent.com/assets/14196612/9845495/ed4421d2-5ae8-11e5-84ec-bb336d2b8ec4.png">


Is there anything i am missing ? Please look into it.
Thanks

**Comment by NickAb** [comment]
Hi,

`findElementByName` uses `AutomationProperties.Name` for matching elements. I think your button does not have such property set on it.

Here is an example of `.xaml` snippet with some TextBox

```xaml
<TextBox
    Name="TextBox1"
    AutomationProperties.AutomationId="MyTextBox"
    AutomationProperties.Name="SomeAutomationName"
/>
```

You will be able to find this element using:
```java
.findElementByName("SomeAutomationName")
```

```java
.findElementById("MyTextBox")
```
```java
.findElementByClassName("System.Windows.Controls.TextBox")
```

Also there is `xname` strategy which will let you find this element using `Name="TextBox1"`, but how to use such strategy depends on language bindings. In python you have to add `xname` to the list of allowed strategies and use `findBy("xname", "TextBox1")` to find it, in java it might be harder to do so.

**Comment by KonyLabs** [comment]
Hi Nick,

I wanted to know that, has there been any trials with winphonedriver for Java support ?
Because when i am trying to access an element by Name its throwing below error.

org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: 

Thanks

**Comment by NickAb** [comment]
Hello,

Sorry but I had no chance to see if it works with Java bindings yet.
To speed up the process, could you please provide driver log and complete stack trace of error (if it is displayed)?

> To get log you should run driver `--verbose` option for logging into console, or with both `--verbose` and `--log-path=FILE` to log to file

**Comment by KonyLabs** [comment]
<img width="1203" alt="screen shot 2015-09-30 at 7 24 48 pm" src="https://cloud.githubusercontent.com/assets/14196612/10194958/00e24ecc-67a9-11e5-8d07-d9bf8e664fb2.png">

**Comment by NickAb** [comment]
It seems that the problem not in compatibility with Java client bindings, but in the fact that the `InnerServer` is not responding.
`"...Unable to connect to the remote server..."` means that your test automation server is not working. Make sure that you deployed the app that includes `InnerServer` and that `InnerServer` is initialised and started correctly. You can try building and deploying test app first, to make sure that it works for your setup.

**Comment by KonyLabs** [comment]
Ahh , yeah the inner server was not set properly.
Its working for Java smoothly.

**Comment by KonyLabs** [comment]
Hi Nick ,

So i started using it. But i guess there are some methods not implemented or i am having problem to execute them. I am listing my issue, maybe you can help me with it : 

1.While performing swipe using execute script it says "execute partially implemented, supports only mobile: prefixed commands" .. is there any work around for swipe?

2.Sliding a slider by a particular amount ? 

3.Not able to toggle switch through click()

4.On clicking radioButton its not being checked.

5.And finally how do we click on native OK/allow/cancel ? findElementByName() is not working for them.

Thanks

**Comment by NickAb** [comment]
Hi @KonyLabs,

Can you please clarify some moments:

1. How do you try to swipe using `ExecuteScript`? (only *StoreApps* driver supports scrolling via `ExecuteScript`). We might introduce this functionality to *Silverlight* once we merge this project to *StoreApps*, or maybe simple back port it if needed. Have you tried using `TouchActions.scroll`? `TouchActions.scroll` is an intended way to scroll fro both this and *StoreApps* drivers.

2. What do you mean by sliding a slider using `sendKeys`? Are you trying to simulate Volume Up/Volume Down hardware buttons?

3. I will have to check this out, does the switch changes its visual state? We had a problem with switch in our app tested with *StoreApps* driver, because we had some custom handler instead of handling a click . If the visual state of the switch is changing, but the code behind ii is not getting fired, then, most likely, one would have to resort to use of [Automation patterns](https://github.com/2gis/Winium.StoreApps/wiki/Command-Execute-Script#use-automationpeerspatterninterface-on-element) instead of clicking, but they are currently implemented only in *StoreApps*. So we either would have to back port them or merge to drivers into one project (which is planned).

4. I will have to take a look at this, does the visual state of the radio button change? Maybe this is same for switch not switching.

5. Are you trying to find and click `MessageDialog` buttons? First can you try using `switchTo().alert(); alert.getText()` to see if driver actually sees the alert. If it sees it, then you can try calling `accept` or `dismiss` methods on the alert, but those methods use [hard coded button names](https://github.com/2gis/winphonedriver/blob/master/WindowsPhoneDriver/WindowsPhoneDriver.InnerDriver/Commands/AlertTextCommand.cs), so it might not work and need some fixes. Also note that popups are treated as a separate windows and can't be accessed using `find element` commands, this was fixed in *StoreApps* and will be fixed in *winphonedriver* once we merge this projects. Also If you can't see message text using driver commands and this dialog is `MessageDialog` then you won't be able to interact with it, as it appears to be opened outside of the main app window, not even in popups (at least this what happens for *StoreApps*). As a workaround we replaced all `MessageDialog`s with `ContentDialog`s, but working with them will still require `findElement` to be fixed in a way as it was fixed in *StoreApps*

**Comment by KonyLabs** [comment]
I tried out whatever you suggested ,

1. I was trying 
    JavascriptExecutor js = (JavascriptExecutor) driver.appy;
   js.executeScript("window.scrollBy(" + xOffset + "," + yOffset+ ")", ""); but this was throwing error.
   So, now i tried TouchActions.scroll() , but somehow this doesn't seem to be working.
   Becuase we are creating Remote WebDriver, and touchAction constructor takes WebDriver  as parametre. I even tried to typecast Remote WebDriver to WebDriver like "TouchActions touch = new TouchActions((WebDriver)driver.appy);" 
 But its throwing this error always(with/without typecasting):    org.openqa.selenium.remote.RemoteWebDriver cannot be cast to  org.openqa.selenium.interactions.HasTouchScreen
What is the solution for this Nick ?

2. Yeah you can say i am trying to simulate volume bar, but i want that to be suppose 75% , how can i do this ? Appium/Selenium, we can do this by swipe() and sendKeys(). Thats not working here.
RIght now on clicking slider it moves by 50%.

3. No the visuality is not changing at all , it just executes click and nothing happens on screen.

4.Visuality not changing , same as switch.

So when you say, you are going to merge both project ? When it is planned ? And after merge you mean  both projects be working through same Inner/Outer Driver?

Thanks

**Comment by NickAb** [comment]
1. You can not use `javascript` in native apps, so `js.executeScript("window.scrollBy(" + xOffset + "," + yOffset+ ")", "");` will not work, but `TouchActions.scroll` will. The error you are getting is due to the fact that default `RemoteWebDriver` does not implement `HasTouchScreen`. To use `TouchActions` you will have to create a new driver class that will inherit from `RemoteWebDriver` and will also implement `HasTouchScreen` interface. More on this along with a link to reference C# implementation can be found [here](https://github.com/2gis/Winium.StoreApps/wiki/Using-TouchActions-in-C%23), it should be easy to reimplement in Java.

2. In Selenium you have web apps where focused element gets all keyboard input and sliders usually, but not necessary, react to arrow keys, I am not sure that in the native Windows Phone application you will be able to move slider using keyboard, but I will check it soon. Meanwhile you can try using `TouchActions.scroll` on the slider, it should work, but might be not as precise as you would like. Once we have Automation patterns backported into this driver, I believe, it would be possible to precisely set ranged elements like sliders.

3. This is strange, could you please check if element's `location` and `location_once_scrolled_into_view` return correct values (you can make a screenshot and place point on it at `location` to check if it is misaligned or not). I will try to interact with some switch element in test app later.

Yes, we would like to merge both project so that easier to maintain and also to make sure that Silverlight gets at least some of the updates that we roll out for StoreApps (as StoreApps is key project for us). Unfortunately there is no concrete deadline on this issue. Also, as a first step, we will have a single (outer) driver implementation, but two different InnerServer implementations but in the same solution and with some fixes and enhancements back-ported to Silverlight from StoreApps. Having single InnerServer for both Silverlight and StoreApps might be a next step if there still will be any interest in Silverlight, as it being phased and replaced by Store/Universal Apps.

**Comment by KonyLabs** [comment]
Dude , i am breaking my Head over this . Please point me out if i am missing anything ?

public class WindowsPhoneDriver extends RemoteWebDriver implements HasTouchScreen {

		private TouchScreen touchScreen;
		
		public WindowsPhoneDriver(CommandExecutor commandExecutor,
			DesiredCapabilities capabilities) {
			super(commandExecutor,capabilities);
		}

		@Override
		public TouchScreen getTouch() {
			this.touchScreen=new RemoteTouchScreen(getExecuteMethod());
			return touchScreen;
		}
}

And I am calling through : 

WindowsPhoneDriver WpDriver;
WpDriver = new WindowsPhoneDriver(commandExecutor, capabilities);

TouchActions touches = new TouchActions(WpDriver);
touches.moveByOffset(0, 200);

And its just executing and nothings happening on screen. :-/

**Comment by NickAb** [comment]
You are missing `touches.perform()`. Also, there are two sets of API: TouchActions and Actions.
I think `touches.moveByOffset(0, 200);` is not implemented and `touches.scroll(0,200);` will always start scroll gesture from the middle of the screen, because it is not specified that this command should start gesture from some state set by previous commands (and so it always starts from middle of the screen).
 > Use this command if you don't care where the scroll starts on the screen.
If you want to scroll from some element, then `TouchActions.scroll(WebElement onElement, int xOffset, int yOffset)` will be the command.

If you need to make a gesture from specific point, then you will have to use Actions and the sequence of commands will be something like: `moveByOffset` or `moveToElement` (to the starting point), `clickAndHold`, `moveByOffset` or `moveToElement` (to the end point), `release`, `perform`.

Note that you have to call `perform` in any case as it is when and only when the commands are actually sent to driver by client (tests).

https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/interactions/touch/TouchActions.html#scroll-int-int-

**Comment by KonyLabs** [comment]
Ahh , Thanks a lot mate.

And hey , i was wondering if this driver can be extended for Tablet and Kiosk(Dektop Web) Application ?

**Comment by NickAb** [comment]
No problem.

For desktop you can try https://github.com/2gis/Winium.Desktop and see if it works for you.

Tablets will need some investigation. Are you talking about Windows RT apps?

**Comment by KonyLabs** [comment]
I meant the tablet Emulator.

Btw, regarding issues with Radiobutton and Switch, whose visualisation behaviour is not changing on clicking over it. I checked the location of these controls which are being returned correct. Please look into it as it is needed for my Project.

And one more doubt, is there any method to select Item from listBox, because the items in listBox won't be having any style, so how can we set AutomationProperties.Name to identify listbox elements ?

Thanks

**Comment by NickAb** [comment]
I've opened issue #54 and will try to look into it soon. Bug me if I get in over my head and forget about this one.

Regarding the ListBox you can try locating list items using `class name` and index, something along the lines of:
```py
item = driver.find_elements_by_class_name('System.Windows.Controls.ListboxItem')[7]
```
You might need to replace `System.Windows.Controls.ListboxItem` with a correct class name.

**Comment by KonyLabs** [comment]
Hi Nick,

While accessing TextBox , if i am trying to getElementByName("TextBox_Text") its throwing error : Element cannot be Found.  And i checked the text of TextBox in Visual studio its being assigning correctly to AutomationProperties.Name key. But with getElementById() is working. Why so?

**Comment by NickAb** [comment]
Hi,

You can use `getPageSource` command to print out all elements that driver can find at the moment the command is called. Page source will be represented as xml where each element will have attributes `id` and `name`, which can be used to find this element.

On 09 Oct 2015, at 23:35, KonyLabs <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Nick,

While accessing TextBox , if i am trying to getElementByName("TextBox_Text") its throwing error : Element cannot be Found. And i checked the text of TextBox in Visual studio its being assigning correctly to AutomationProperties.Name key. But with getElementById() is working. Why so?

**Comment by KonyLabs** [comment]
Yeah i made it work. Anyhow thanks for the suggestion, this would be really helpful.

**Comment by KonyLabs** [comment]
Nick, how can we find an element by value which is displayed by getPageSource.
Like this example :  
<System.Windows.Controls.TextBlock name="" id="" xname="" visible="true" value="Tab2" x="92" y="805" />

How to find by Tab2 ? And xpath is not same as xname ? right ? coz it doesn't work.

**Comment by NickAb** [comment]
`xpath` is an xml path language and is not supported, because libraries needed to make it work were not available in mobile apps.
`xname` is used to search elements by [`x:Name` attribute](https://msdn.microsoft.com/en-us/library/cc189028(VS.95).aspx) and it is not the same as `xpath`. You ca see and example of how to use `xname` locator in compiled language [here](https://github.com/2gis/Winium.StoreApps/blob/master/Winium/TestApp.Test/Samples/WpDriver.cs#L67).
I would recommend to attach `AutomationProperties.AutomationId` or `AutomationProperties.Name` to the element you want to find if it is possible.
You have all attributes (`id`, `name`, `xname`) empty, except for `class name` and unfortunately there is not support for finding by element text, but you can find all elements by `class name`==`System.Windows.Controls.TextBlock` and then iterate them to find the one where `getText`==`Tab2`. It is recommended to narrow the search, os if you have any parent element with `id` or `name`, then I would recommend to find this element first and the search elements tarting from this element.

**Comment by KonyLabs** [comment]
Yeah, but it should have some name then only we can use getText ? Anyhow i will figure some workaround in the backend code.

Nick, i am stuck with Listbox. So I am not able to see the exposed listBoxItems through getPageSource(). 
I will describe you my procedure, maybe you can help me on it.
In the windows platform side i am creating a ListBox and adding  ListBoxItems to it.
<img width="878" alt="screen shot 2015-10-13 at 2 48 49 pm" src="https://cloud.githubusercontent.com/assets/14196612/10450708/b9c0ba54-71b9-11e5-85d3-fceacc77ae2d.png">

But in the Xml obtained through getPageSource() (after hitting the ListBoxItems popup in the app), i can't find this class System.Windows.Controls.ListBox ? 
And i am very new to visual studio and windows phone environment, so maybe i am missing something but not having any clue on how to debug.

**Comment by NickAb** [comment]
So the list box you want to find is displayed on screen when you are trying to find it?
Can you find `System.Windows.Controls.ListBox` or `System.Windows.Controls.ListBoxItem` using `findElementsByClassName`?

It would help if you could provide `xml` output of your page source and screenshot with element that you want to find, if it can be provided. Make sure to remove any private information from `xml` if you have it in element values, etc.

**Comment by NickAb** [comment]
> Yeah, but it should have some name then only we can use getText ? Anyhow i will figure some workaround in the backend code.

You can always find elements by their `class name` and then iterate over found elements to check if text matches the one you need. You can find elements even if the don't have `name` or `id`, as they will always have `class name`.

**Comment by NickAb** [comment]
The `xml` part you provided only shows the `Framework.comboboxControl` with *Flower* element selected which is the one that is behind popup list of three items (Flower, Vegetable, Phone).

You should look for popup if it is visible to driver (and it might be not). Could you please try `findelementsByClassName("System.Windows.Controls.TextBlock")` and check if any of them has `Phone` or `Vegetable` value when combobox is in expanded state. If not, then the elements are in a separate tree in popup child, i.e. command for finding elements will need a fix.

Also a compete `getPageSource` as a text file will also help.

**Comment by NickAb** [comment]
Could you try out InnerServer build from branch https://github.com/2gis/winphonedriver/tree/find-popup-elements. I have added popup children elements to searchable tree and page source. But it will only work in case if popups are showed as not blocking, e.g. it will not work for MessageBox.Show. Finding elements is done on UI thread and `MessageBox.Show` when called on UI thread will block it.

**Comment by KonyLabs** [comment]
There is no textblock for Phone/Vegetable and moreover there is no class with name System.Controls.Listbox/ListboxItems. That is what made me wonder, how to access them.

I tried with the New Inner Server , things looks same.
I am attaching the whole XML Content and elements screenshot.
<img width="316" alt="screen shot 2015-10-14 at 12 10 33 pm" src="https://cloud.githubusercontent.com/assets/14196612/10476565/a09f577a-726c-11e5-84cb-b02064337194.png">

http://ideone.com/GmuAWm 

And moreover the XML content for Home Page and the ListBoxItem Popup Page is not changing ? getPageSource returns the current form data not of the whole application right ? So it should change.

**Comment by NickAb** [comment]
@KonyLabs latest master should expose AppBar and popups (but not the shell).

Can I close this issue or do you have other unanswered questions?

**Comment by KonyLabs** [comment]
@NickAb , we can close this for now. I may get back to you if i'll get stuck with anything, once i start working on it again.
