### ISSUE TITLE
How will i come to know if my inner server is initialized correctly? 

### ISSUE THREAD

**Issue by padmaja2812** [2gis/winphonedriver#73]
Is there a way to find if inner server is running ?

**Comment by NickAb** [comment]
There are a few options, here are some:
1. You can try running empty test case, so that a new session will get created, the app will launch and the driver will try to connect to it. Driver will throw an error if it would not be able to connect to inner server.

2. Or you can try posting following json in body `{ "name": "ping" }` using POST request to `localhost:9998`.

3. Set breakpoint on line where you init Inner Server (`AutomationServer.Instance.InitializeAndStart`) and launch your app in Debug mode. Check if it hits the break point, then step into and make sure that initialisation works.

**Comment by padmaja2812** [comment]
Thanks Nick.
 I  tried with debug point it is starting Inner server but when  i am running app from my test case,the  outer driver is trying to connect to inner server ,its giving no response.This exception is thrown sometimes "**Package failed updates, dependency or conflict validation silverlight**"Whereas i am able to deploy it from VS as well as deployment tool.
Can you give some suggestion for the same.

Thanks
Padmaja

**Comment by NickAb** [comment]
Make sure that you specify path to xap/appx package that is build for x86 architecture (not arm).
Try closing emulator and running test again, it will start clean emulator.

The debug point method will work only if you start your app under a test using debug in VS and will use `debugConnectToRunningApp ` capability in your tests, or else driver will try to uninstall the app you are debuting and redeploy it, so you will lose debug session and won't be able to hit break points.

**Comment by padmaja2812** [comment]
I am using x86 architecture and restarting emulator.
Can you please elaborate more on "start app under test using debug in vs".

Currently i am writing a  console application where I am setting these capabilities 
var dc = new DesiredCapabilities();
        dc.SetCapability(CapabilityType.Version, "8.1");
        dc.SetCapability(CapabilityType.Platform, "WindowsPhone");
        dc.SetCapability("launchDelay","2000");
        dc.SetCapability("DeviceName", "Emulator 8.1 WVGA 4 inch 512MB");
        dc.SetCapability("launchTimeout","2000");
        dc.SetCapability("app", @"C:\WindowsPhone\windowsphone8\ABC_Debug_x86.xap");
        Driver = new RemoteWebDriver(new Uri("http://localhost:9999"), dc);
And have added startautomation server to my app.xmal.cs.

**Comment by NickAb** [comment]
You can open you app under a test project in Visual Studio and run it in debug mode. Then you will be able to hit breakpoints and check if `AutomationServer.Instance.InitializeAndStart ` does run (note that if you run test without `debugConnectToRunningApp ` capability, then driver will uninstall the instance of the app that Visual Studio debugger is connected to).

Afterwards you can try posting a ping command using `curl` or REST console.

**Comment by NickAb** [comment]
Do you use exactaly this code to add Inner server to your app under a test?
```
#if DEBUG
    AutomationServer.Instance.InitializeAndStart(RootFrame);
#endif // DEBUG
```

If so, make sure to build and package your app using DEBUG configuration and to specify path to the DEBUG package. As the driver will not get started in RELEASE or any other configuration, except DEBUG.

**Comment by padmaja2812** [comment]
Thanks for the quick response.
I have already done this and able to debug the application.
Is there a need to add "**WindowsPhoneDriver.Common**" to my test or my App ?

**Comment by NickAb** [comment]
If you add InnerServer as NuGet package, then there is no need to reference `WindowsPhoneDriver.Common` as it will be added automatically.
If you add references manually, then you will need to reference both InnerServer and Common.

**Comment by padmaja2812** [comment]
I  add a reference in the app.
Do i need to call some function in app code?
When i am running my test I am getting this error.
Field not found: 
"WindowsPhoneDriver.Common.DriverCommand.GetElementRect"

**Comment by NickAb** [comment]
1. Make sure you compiled both InnerDriver and Common from the same revisions.
2. Add references to both assemblies to your app project.
3. Do step 3 from https://github.com/2gis/winphonedriver#usage

---

Note that step 2 in https://github.com/2gis/winphonedriver#usage erroniously states that only InnerServer needs to be added as reference, this is likely because it was phrased with NuGet package in mind (where you need to install one package only and all assemblies will be referenced automatically).
I will double check it and fix it later https://github.com/2gis/winphonedriver/issues/74.
